MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - "10.12"                # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - "10.12"                # [osx]
cxx_compiler:              # [win]
  - vs2019                 # [win]