name: Conda

on: 
  workflow_dispatch:
    inputs:
      should_publish:
        description: 'Should publish to Anaconda'
        required: false
        type: boolean
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-2019, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v3

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Prepare
        run: conda install conda-build conda-verify
        
      - name: Build
        run: |
          mkdir build
          conda build conda -c conda-forge --no-anaconda-upload --output-folder build
        
      - name: Install
        run: conda install -c build/ phonetisaurus-py

      - name: Find and export artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/*/phonetisaurus-py**.tar.bz2
          
      - name: Setup Anaconda client
        if: github.event_name == 'push' || inputs.should_publish
        run: conda install -y anaconda-client
        
      - name: Upload to Anaconda (win-64)
        if: ${{ (github.event_name == 'push' || inputs.should_publish) && runner.os == 'Windows' }}
        run: anaconda upload build/win-64/*.tar.bz2
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      - name: Upload to Anaconda (linux-64)
        if: ${{ (github.event_name == 'push' || inputs.should_publish) && runner.os == 'Linux' }}
        run: anaconda upload build/conda-bld/linux-64/*.tar.bz2
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      - name: Upload to Anaconda (osx-64)
        if: ${{ (github.event_name == 'push' || inputs.should_publish) && runner.os == 'macOS' }}
        run: anaconda upload build/conda-bld/osx-64/*.tar.bz2
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
